### ISSUE TITLE
Cannot build on native applications

### ISSUE THREAD

**Issue by Tekdey** [tamagui/starter-free#59]
I have been encountering the same issue for the past three days, where I am unable to build my native apps. This error started appearing after upgrading from Expo 51 to Expo 52 and React Native from 0.74.5 to 0.76.6. I use EAS to build my applications, and the error is related to react-native-svg, as shown in the screenshot below.

<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/ab727556-9386-4d2f-91a6-5c316b91d3bb" />

I copied the same library from the packages in the monorepo starter [v1.125.20](https://github.com/tamagui/starter-free/commit/c3b18eaf8f3a75987f3e3c43d3e29a4e0e59d479).

./package.json : 

```json
{
...

"resolutions": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-refresh": "^0.14.0",
    "react-native-svg": "15.3.0",
    "react-native-web": "~0.19.12"
  },
  "dependencies": {
    "@babel/runtime": "^7.24.6",
    "@formidable-webview/webshell": "^2.6.0",
    "@manypkg/cli": "^0.21.3",
    "@rehookify/datepicker": "^6.6.8",
    "@tamagui/cli": "^1.125.20",
    "@tanstack/react-table": "^8.20.5",
    "check-dependency-version-consistency": "^4.1.0",
    "date-fns": "^3.6.0",
    "eslint": "^9.3.0",
    "expo-updates": "~0.25.27",
    "firebase": "^10.8.0",
    "husky": "^9.1.6",
    "jwt-decode": "^3.1.2",
    "local-ssl-proxy": "^2.0.5",
    "next-redux-wrapper": "^8.1.0",
    "node-gyp": "^10.0.1",
    "prettier": "^3.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "turbo": "^1.13.4",
    "typescript": "^5.6.2",
    "ultra-runner": "^3.10.5",
    "vitest": "^2.1.1"
  },
  "packageManager": "yarn@4.5.0",
  "engines": {
    "node": "22",
    "npm": "10.8"
  },
  "devDependencies": {
    "@babel/plugin-transform-export-namespace-from": "^7.23.4",
    "@biomejs/biome": "1.9.3",
    "@types/jest": "^29.5.12",
    "dotenv-cli": "^7.4.1",
    "jest": "^29.7.0",
    "lefthook": "^1.6.7",
    "ts-jest": "^29.1.2"
  }
}
```

./packages/ui/packages.json : 

```json
{
...
"dependencies": {
    "@tamagui-extras/file": "^1.12.0",
    "@tamagui-extras/form": "^1.17.0",
    "@tamagui/animations-css": "^1.74.21",
    "@tamagui/animations-moti": "^1.125.20",
    "@tamagui/animations-react-native": "^1.125.20",
    "@tamagui/font-inter": "^1.125.20",
    "@tamagui/react-native-media-driver": "^1.125.20",
    "@tamagui/sheet": "^1.125.20",
    "@tamagui/shorthands": "^1.125.20",
    "@tamagui/switch": "^1.88.1",
    "@tamagui/themes": "^1.125.20",
    "@tamagui/toast": "^1.125.20",
    "tamagui": "^1.125.20",
    "tamagui-multiple-select": "^1.22.4"
  },
  "devDependencies": {
    "@tamagui/build": "^1.125.20"
  }
```

packages/app/packages.json
```json 
{
...
"dependencies": {
    "@my/ui": "0.4.2",
    "@react-navigation/native": "^6.1.17",
    "@tamagui/animations-css": "^1.74.21",
    "@tamagui/animations-react-native": "^1.125.20",
    "@tamagui/colors": "^1.125.20",
    "@tamagui/font-inter": "^1.125.20",
    "@tamagui/lucide-icons": "^1.125.20",
    "@tamagui/shorthands": "^1.125.20",
    "@tamagui/themes": "^1.125.20",
    "@tanstack/react-query": "^5.28.14",
    "@tanstack/react-query-devtools": "^5.29.2",
    "axios": "1.5.1",
    "burnt": "^0.12.2",
    "chart.js": "^4.4.3",
    "chartjs-plugin-annotation": "^3.0.1",
    "chartjs-react": "^4.2.1",
    "dom-to-image-more": "^3.5.0",
    "expo-camera": "^15.0.11",
    "expo-constants": "~16.0.2",
    "expo-document-picker": "^12.0.2",
    "expo-image": "^1.12.12",
    "expo-linking": "~6.3.1",
    "i18next": "^23.12.2",
    "jwt-decode": "^3.1.2",
    "patternomaly": "^1.3.2",
    "react-chartjs-2": "^5.2.0",
    "react-hook-form": "^7.54.2",
    "react-i18next": "^15.0.1",
    "react-native-safe-area-context": "4.10.4",
    "react-native-svg": "15.3.0",
    "socket.io-client": "^4.7.2",
    "solito": "^4.2.2",
    "zustand": "^5.0.3"
  },
  "devDependencies": {
    "@types/googlemaps": "^3.43.3",
    "@types/react": "^18.3.3",
    "@types/react-native": "^0.73.0"
  }
}
```

apps/next/packages.json

```json
{
...
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "@sentry/nextjs": "^8.54.0",
    "@sentry/profiling-node": "^8.54.0",
    "@tamagui/config": "^1.125.20",
    "@tamagui/next-theme": "^1.125.20",
    "app": "0.4.2",
    "cookies-next": "^4.2.1",
    "google-maps-react": "^2.0.6",
    "mini-css-extract-plugin": "^2.9.1",
    "next": "14.2.14",
    "next-auth": "^4.24.6",
    "next-i18next": "^15.3.1",
    "raf": "^3.4.1",
    "react": "^18.3.1",
    "react-camera-pro": "1.3.0",
    "react-dom": "^18.3.1",
    "react-native": "0.76.7",
    "react-native-web": "0.19.12",
    "react-native-web-lite": "^1.112.4",
    "react-player": "^2.16.0",
    "react-signature-canvas": "^1.0.6",
    "rxjs": "^7.8.1",
    "sharp": "^0.33.0",
    "styled-components": "6.1.8",
    "tamagui": "^1.125.20",
    "vercel": "latest"
  },
  "devDependencies": {
    "@tamagui/next-plugin": "^1.125.20",
    "@types/node": "^20.14.1",
    "eslint-config-next": "^14.2.3",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^10.0.1",
    "tree-kill": "^1.2.2",
    "vitest": "^2.1.1"
  }
}

```

apps/expo/packages.json 

```json
{
...

"dependencies": {
    "@babel/runtime": "^7.26.0",
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo-google-fonts/work-sans": "^0.2.3",
    "@expo/config-plugins": "9.0.14",
    "@my/ui": "0.4.2",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native/assets-registry": "0.76.6",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@shopify/flash-list": "1.7.3",
    "app": "0.4.2",
    "babel-plugin-module-resolver": "^5.0.2",
    "burnt": "^0.12.2",
    "expo": "52.0.37",
    "expo-build-properties": "~0.13.2",
    "expo-constants": "17.0.7",
    "expo-dev-client": "5.0.12",
    "expo-device": "~7.0.2",
    "expo-file-system": "~18.0.11",
    "expo-font": "13.0.4",
    "expo-image-picker": "~16.0.4",
    "expo-linear-gradient": "14.0.2",
    "expo-linking": "7.0.5",
    "expo-localization": "~16.0.1",
    "expo-location": "~18.0.7",
    "expo-media-library": "~17.0.5",
    "expo-notifications": "~0.29.13",
    "expo-router": "4.0.17",
    "expo-splash-screen": "0.29.22",
    "expo-status-bar": "2.0.1",
    "expo-system-ui": "~4.0.7",
    "expo-updates": "~0.27.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-native": "0.76.7",
    "react-native-canvas": "^0.1.39",
    "react-native-canvas-signature": "^1.0.2",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-maps": "1.18.0",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-svg": "15.8.0",
    "react-native-web": "0.19.12",
    "react-native-webview": "13.12.5",
    "supports-color": "^9.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.6",
    "@expo/metro-config": "0.19.9",
    "@tamagui/babel-plugin": "^1.125.20",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "colors": "^1.4.0",
    "metro-minify-terser": "^0.81.0",
    "typescript": "^5.7.3"
  },
  "resolutions": {
    "metro": "0.81.0",
    "metro-resolver": "0.81.0"
  },
  "overrides": {
    "metro": "0.81.0",
    "metro-resolver": "0.81.0"
  }

}
...

}

```

**Comment by natew** [comment]
Sorry about this - We've just merged some fixes, let me know if they fix. @baronha can help further if it's still breaking.

**Comment by baronha** [comment]
Please check the latest version @Tekdey !

**Comment by Tekdey** [comment]
I updated to the latest version, but I still cannot build the native app. I encountered an error with react-native-webview, which I resolved by installing a version compatible with React Native 0.77.

![Image](https://github.com/user-attachments/assets/f75e61bd-d8aa-480d-ba09-d686942197fa)

After rebuilding, I encountered an issue with expo-image, which was fixed by using expo-image 2.0.6.

![Image](https://github.com/user-attachments/assets/f97a0dcb-f710-4857-8717-40e408ad0e35)

After rebuilding again, an error occurred :app:checkReleaseDuplicateClasses, and I’m not sure what it is.

![Image](https://github.com/user-attachments/assets/54209733-3d0b-4328-b36a-b769ef964942)

I resolved all dependencies error, and used expo-doctor.


./packages.json 

```json
{
...
 "resolutions": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-refresh": "^0.14.0",
    "react-native-svg": "15.11.2",
    "react-native-web": "~0.19.12"
  },
  "dependencies": {
    "@babel/runtime": "^7.24.6",
    "@formidable-webview/webshell": "^2.6.0",
    "@manypkg/cli": "^0.21.3",
    "@rehookify/datepicker": "^6.6.8",
    "@tamagui/cli": "^1.125.22",
    "@tanstack/react-table": "^8.20.5",
    "check-dependency-version-consistency": "^4.1.0",
    "date-fns": "^3.6.0",
    "eslint": "^9.3.0",
    "expo-updates": "~0.25.27",
    "firebase": "^10.8.0",
    "husky": "^9.1.6",
    "jwt-decode": "^3.1.2",
    "local-ssl-proxy": "^2.0.5",
    "next-redux-wrapper": "^8.1.0",
    "node-gyp": "^10.0.1",
    "prettier": "^3.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "turbo": "^1.13.4",
    "typescript": "^5.6.2",
    "ultra-runner": "^3.10.5",
    "vitest": "^2.1.1"
  },
  "packageManager": "yarn@4.5.0",
  "engines": {
    "node": "22",
    "npm": "10.8"
  },
  "devDependencies": {
    "@babel/plugin-transform-export-namespace-from": "^7.23.4",
    "@biomejs/biome": "1.9.3",
    "@types/jest": "^29.5.12",
    "dotenv-cli": "^7.4.1",
    "jest": "^29.7.0",
    "lefthook": "^1.6.7",
    "ts-jest": "^29.1.2"
  }
}
```

./packages/ui/package.json

```json
{
...
"dependencies": {
    "@tamagui-extras/file": "^1.12.0",
    "@tamagui-extras/form": "^1.17.0",
    "@tamagui/animations-css": "^1.74.21",
    "@tamagui/animations-moti": "^1.125.22",
    "@tamagui/animations-react-native": "^1.125.22",
    "@tamagui/font-inter": "^1.125.22",
    "@tamagui/react-native-media-driver": "^1.125.22",
    "@tamagui/sheet": "^1.125.22",
    "@tamagui/shorthands": "^1.125.22",
    "@tamagui/switch": "^1.88.1",
    "@tamagui/themes": "^1.125.22",
    "@tamagui/toast": "^1.125.22",
    "tamagui": "^1.125.22",
    "tamagui-multiple-select": "^1.22.4"
  },
  "devDependencies": {
    "@tamagui/build": "^1.125.22"
  }
}
````


./packages/app/package.json

```json
{
...
 "dependencies": {
    "@my/ui": "0.4.2",
    "@react-navigation/native": "^6.1.17",
    "@tamagui/animations-css": "^1.74.21",
    "@tamagui/animations-react-native": "^1.125.22",
    "@tamagui/colors": "^1.125.22",
    "@tamagui/font-inter": "^1.125.22",
    "@tamagui/lucide-icons": "^1.125.22",
    "@tamagui/shorthands": "^1.125.22",
    "@tamagui/themes": "^1.125.22",
    "@tanstack/react-query": "^5.28.14",
    "@tanstack/react-query-devtools": "^5.29.2",
    "axios": "1.5.1",
    "burnt": "^0.12.2",
    "chart.js": "^4.4.3",
    "chartjs-plugin-annotation": "^3.0.1",
    "chartjs-react": "^4.2.1",
    "dom-to-image-more": "^3.5.0",
    "expo-camera": "^15.0.11",
    "expo-constants": "~16.0.2",
    "expo-document-picker": "^12.0.2",
    "expo-image": "^1.12.12",
    "expo-linking": "~6.3.1",
    "i18next": "^23.12.2",
    "jwt-decode": "^3.1.2",
    "patternomaly": "^1.3.2",
    "react-chartjs-2": "^5.2.0",
    "react-hook-form": "^7.54.2",
    "react-i18next": "^15.0.1",
    "react-native-safe-area-context": "5.2.0",
    "react-native-svg": "15.3.0",
    "socket.io-client": "^4.7.2",
    "solito": "^4.2.2",
    "zustand": "^5.0.3"
  },
  "devDependencies": {
    "@types/googlemaps": "^3.43.3",
    "@types/react": "^18.3.3",
    "@types/react-native": "^0.73.0"
  }
}
```

./apps/next/packages.json

```json
{

...,
"dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "@sentry/nextjs": "^8.54.0",
    "@sentry/profiling-node": "^8.54.0",
    "@tamagui/config": "^1.125.22",
    "@tamagui/next-theme": "^1.125.22",
    "app": "0.4.2",
    "cookies-next": "^4.2.1",
    "google-maps-react": "^2.0.6",
    "mini-css-extract-plugin": "^2.9.1",
    "next": "14.2.14",
    "next-auth": "^4.24.6",
    "next-i18next": "^15.3.1",
    "raf": "^3.4.1",
    "react": "^18.3.1",
    "react-camera-pro": "1.3.0",
    "react-dom": "^18.3.1",
    "react-native": "0.77.0",
    "react-native-web": "0.19.12",
    "react-native-web-lite": "^1.112.4",
    "react-player": "^2.16.0",
    "react-signature-canvas": "^1.0.6",
    "rxjs": "^7.8.1",
    "sharp": "^0.33.0",
    "styled-components": "6.1.8",
    "tamagui": "^1.125.22",
    "vercel": "latest"
  },
  "devDependencies": {
    "@tamagui/next-plugin": "^1.125.22",
    "@types/node": "^20.14.1",
    "eslint-config-next": "^14.2.3",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^10.0.1",
    "tree-kill": "^1.2.2",
    "vitest": "^2.1.1"
  }
}
```

apps/expo/packages.json

```json
{
...
"dependencies": {
    "@babel/runtime": "^7.26.0",
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo-google-fonts/work-sans": "^0.2.3",
    "@expo/config-plugins": "9.0.14",
    "@my/ui": "0.4.2",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native/assets-registry": "0.76.6",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@shopify/flash-list": "1.7.3",
    "app": "0.4.2",
    "babel-plugin-module-resolver": "^5.0.2",
    "burnt": "^0.12.2",
    "expo": "52.0.37",
    "expo-build-properties": "~0.13.2",
    "expo-constants": "17.0.7",
    "expo-dev-client": "5.0.12",
    "expo-device": "~7.0.2",
    "expo-file-system": "~18.0.11",
    "expo-font": "13.0.4",
    "expo-image": "^2.0.6",
    "expo-image-picker": "~16.0.6",
    "expo-linear-gradient": "14.0.2",
    "expo-linking": "7.0.5",
    "expo-localization": "~16.0.1",
    "expo-location": "~18.0.7",
    "expo-media-library": "~17.0.6",
    "expo-notifications": "~0.29.13",
    "expo-router": "4.0.17",
    "expo-splash-screen": "0.29.22",
    "expo-status-bar": "2.0.1",
    "expo-system-ui": "~4.0.8",
    "expo-updates": "~0.27.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-native": "0.76.7",
    "react-native-canvas": "^0.1.39",
    "react-native-canvas-signature": "^1.0.2",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-maps": "1.18.0",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-svg": "15.8.0",
    "react-native-web": "0.19.12",
    "react-native-web-lite": "^1.112.4",
    "react-native-webview": "13.12.5",
    "supports-color": "^9.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@expo/metro-config": "~0.19.0",
    "@tamagui/babel-plugin": "latest",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "colors": "^1.4.0",
    "metro-minify-terser": "^0.74.1",
    "typescript": "~5.3.3"
  },
  "resolutions": {
    "metro": "0.81.0",
    "metro-resolver": "0.81.0"
  },
  "overrides": {
    "metro": "0.81.0",
    "metro-resolver": "0.81.0"
  }

}

```

**Comment by natew** [comment]
Closing - this appears to be a build issue specific to your project setup rather than a bug in starter-free.
